
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.bloxycraftingdead.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;

import net.mcreator.bloxycraftingdead.block.WreckedTVBlock;
import net.mcreator.bloxycraftingdead.block.WreckedStopSignBlock;
import net.mcreator.bloxycraftingdead.block.WreckedFlatscreenBlock;
import net.mcreator.bloxycraftingdead.block.WorkingLaptopBlock;
import net.mcreator.bloxycraftingdead.block.WorkingComputerBlock;
import net.mcreator.bloxycraftingdead.block.WorkbenchBlock;
import net.mcreator.bloxycraftingdead.block.Woodenbarricadewindow03cBlock;
import net.mcreator.bloxycraftingdead.block.Woodenbarricadewindow03bBlock;
import net.mcreator.bloxycraftingdead.block.Woodenbarricadewindow03aBlock;
import net.mcreator.bloxycraftingdead.block.Woodenbarricadewindow02bBlock;
import net.mcreator.bloxycraftingdead.block.Woodenbarricadewindow01cBlock;
import net.mcreator.bloxycraftingdead.block.Woodenbarricadewindow01bBlock;
import net.mcreator.bloxycraftingdead.block.WoodenBarricadeWindow03Block;
import net.mcreator.bloxycraftingdead.block.WoodenBarricadeWindow02cBlock;
import net.mcreator.bloxycraftingdead.block.WoodenBarricadeWindow02aBlock;
import net.mcreator.bloxycraftingdead.block.WoodenBarricadeWindow02Block;
import net.mcreator.bloxycraftingdead.block.WoodenBarricadeWindow01aBlock;
import net.mcreator.bloxycraftingdead.block.WoodenBarricadeWindow01Block;
import net.mcreator.bloxycraftingdead.block.WearedTurnedBarrelRedBlock;
import net.mcreator.bloxycraftingdead.block.WearedTurnedBarrelGreyBlock;
import net.mcreator.bloxycraftingdead.block.WearedTurnedBarrelGreenBlock;
import net.mcreator.bloxycraftingdead.block.WearedTurnedBarrelBlueBlock;
import net.mcreator.bloxycraftingdead.block.WearedBarrelRedBlock;
import net.mcreator.bloxycraftingdead.block.WearedBarrelGreyBlock;
import net.mcreator.bloxycraftingdead.block.WearedBarrelGreenBlock;
import net.mcreator.bloxycraftingdead.block.WearedBarrelBlueBlock;
import net.mcreator.bloxycraftingdead.block.UsedToiletBlock;
import net.mcreator.bloxycraftingdead.block.UsedDirtyToiletBlock;
import net.mcreator.bloxycraftingdead.block.TurnedOfficeChairBlock;
import net.mcreator.bloxycraftingdead.block.TurnedGasCanRedBlock;
import net.mcreator.bloxycraftingdead.block.TurnedGasCanGreenBlock;
import net.mcreator.bloxycraftingdead.block.TurnedGasCanBlueBlock;
import net.mcreator.bloxycraftingdead.block.TurnedDirtyOfficeChairBlock;
import net.mcreator.bloxycraftingdead.block.TurnedBarrelRedBlock;
import net.mcreator.bloxycraftingdead.block.TurnedBarrelGreyBlock;
import net.mcreator.bloxycraftingdead.block.TurnedBarrelGreenBlock;
import net.mcreator.bloxycraftingdead.block.TurnedBarrelBlueBlock;
import net.mcreator.bloxycraftingdead.block.Tool04Block;
import net.mcreator.bloxycraftingdead.block.Tool03Block;
import net.mcreator.bloxycraftingdead.block.Tool02Block;
import net.mcreator.bloxycraftingdead.block.Tool01Block;
import net.mcreator.bloxycraftingdead.block.ToiletBlock;
import net.mcreator.bloxycraftingdead.block.TallStopSignBlock;
import net.mcreator.bloxycraftingdead.block.TVBlock;
import net.mcreator.bloxycraftingdead.block.Storeshelfempty04aBlock;
import net.mcreator.bloxycraftingdead.block.Storeshelfempty04Block;
import net.mcreator.bloxycraftingdead.block.Storeshelfempty03aBlock;
import net.mcreator.bloxycraftingdead.block.Storeshelfempty03Block;
import net.mcreator.bloxycraftingdead.block.Storeshelfempty02aBlock;
import net.mcreator.bloxycraftingdead.block.Storeshelfempty02Block;
import net.mcreator.bloxycraftingdead.block.Storeshelfempty01aBlock;
import net.mcreator.bloxycraftingdead.block.Storeshelfempty01Block;
import net.mcreator.bloxycraftingdead.block.Storeshelfcan04aBlock;
import net.mcreator.bloxycraftingdead.block.Storeshelfcan04Block;
import net.mcreator.bloxycraftingdead.block.Storeshelfcan03aBlock;
import net.mcreator.bloxycraftingdead.block.Storeshelfcan03Block;
import net.mcreator.bloxycraftingdead.block.Storeshelfcan02aBlock;
import net.mcreator.bloxycraftingdead.block.Storeshelfcan02Block;
import net.mcreator.bloxycraftingdead.block.Storeshelfcan01aBlock;
import net.mcreator.bloxycraftingdead.block.Storeshelfcan01Block;
import net.mcreator.bloxycraftingdead.block.Storeshelfbox04aBlock;
import net.mcreator.bloxycraftingdead.block.Storeshelfbox04Block;
import net.mcreator.bloxycraftingdead.block.Storeshelfbox03aBlock;
import net.mcreator.bloxycraftingdead.block.Storeshelfbox03Block;
import net.mcreator.bloxycraftingdead.block.Storeshelfbox02aBlock;
import net.mcreator.bloxycraftingdead.block.Storeshelfbox02Block;
import net.mcreator.bloxycraftingdead.block.Storeshelfbox01aBlock;
import net.mcreator.bloxycraftingdead.block.Storeshelfbox01Block;
import net.mcreator.bloxycraftingdead.block.Speed45signBlock;
import net.mcreator.bloxycraftingdead.block.Speed40SignBlock;
import net.mcreator.bloxycraftingdead.block.Speed35SignBlock;
import net.mcreator.bloxycraftingdead.block.Speed30SignBlock;
import net.mcreator.bloxycraftingdead.block.Speed25SignBlock;
import net.mcreator.bloxycraftingdead.block.Speed20SignBlock;
import net.mcreator.bloxycraftingdead.block.SolarpanelBlock;
import net.mcreator.bloxycraftingdead.block.Skeleton032Block;
import net.mcreator.bloxycraftingdead.block.Skeleton031Block;
import net.mcreator.bloxycraftingdead.block.Skeleton030Block;
import net.mcreator.bloxycraftingdead.block.Skeleton022ft2Block;
import net.mcreator.bloxycraftingdead.block.Skeleton022et2Block;
import net.mcreator.bloxycraftingdead.block.Skeleton022dt2Block;
import net.mcreator.bloxycraftingdead.block.Skeleton022ct2Block;
import net.mcreator.bloxycraftingdead.block.Skeleton022bt2Block;
import net.mcreator.bloxycraftingdead.block.Skeleton022at2Block;
import net.mcreator.bloxycraftingdead.block.Skeleton021ft2Block;
import net.mcreator.bloxycraftingdead.block.Skeleton021et2Block;
import net.mcreator.bloxycraftingdead.block.Skeleton021dt2Block;
import net.mcreator.bloxycraftingdead.block.Skeleton021ct2Block;
import net.mcreator.bloxycraftingdead.block.Skeleton021bt2Block;
import net.mcreator.bloxycraftingdead.block.Skeleton021at2Block;
import net.mcreator.bloxycraftingdead.block.Skeleton021Block;
import net.mcreator.bloxycraftingdead.block.Skeleton020ft2Block;
import net.mcreator.bloxycraftingdead.block.Skeleton020et2Block;
import net.mcreator.bloxycraftingdead.block.Skeleton020dt2Block;
import net.mcreator.bloxycraftingdead.block.Skeleton020ct2Block;
import net.mcreator.bloxycraftingdead.block.Skeleton020bt2Block;
import net.mcreator.bloxycraftingdead.block.Skeleton020at2Block;
import net.mcreator.bloxycraftingdead.block.Skeleton020Block;
import net.mcreator.bloxycraftingdead.block.Skeleton012ft1Block;
import net.mcreator.bloxycraftingdead.block.Skeleton012et1Block;
import net.mcreator.bloxycraftingdead.block.Skeleton012dt1Block;
import net.mcreator.bloxycraftingdead.block.Skeleton012ct1Block;
import net.mcreator.bloxycraftingdead.block.Skeleton012bt1Block;
import net.mcreator.bloxycraftingdead.block.Skeleton012at1Block;
import net.mcreator.bloxycraftingdead.block.Skeleton011ft1Block;
import net.mcreator.bloxycraftingdead.block.Skeleton011et1Block;
import net.mcreator.bloxycraftingdead.block.Skeleton011dt1Block;
import net.mcreator.bloxycraftingdead.block.Skeleton011ct1Block;
import net.mcreator.bloxycraftingdead.block.Skeleton011bt1Block;
import net.mcreator.bloxycraftingdead.block.Skeleton011at1Block;
import net.mcreator.bloxycraftingdead.block.Skeleton011Block;
import net.mcreator.bloxycraftingdead.block.Skeleton010ft1Block;
import net.mcreator.bloxycraftingdead.block.Skeleton010et1Block;
import net.mcreator.bloxycraftingdead.block.Skeleton010dt1Block;
import net.mcreator.bloxycraftingdead.block.Skeleton010ct1Block;
import net.mcreator.bloxycraftingdead.block.Skeleton010bt1Block;
import net.mcreator.bloxycraftingdead.block.Skeleton010at1Block;
import net.mcreator.bloxycraftingdead.block.Skeleton010Block;
import net.mcreator.bloxycraftingdead.block.SinkBlock;
import net.mcreator.bloxycraftingdead.block.PowerboxBlock;
import net.mcreator.bloxycraftingdead.block.OfficeChairBlock;
import net.mcreator.bloxycraftingdead.block.O212Block;
import net.mcreator.bloxycraftingdead.block.O1Block;
import net.mcreator.bloxycraftingdead.block.MirrorBlock;
import net.mcreator.bloxycraftingdead.block.Militaryradioslab05Block;
import net.mcreator.bloxycraftingdead.block.Militaryradioslab04Block;
import net.mcreator.bloxycraftingdead.block.Militaryradioslab03Block;
import net.mcreator.bloxycraftingdead.block.Militaryradioslab02Block;
import net.mcreator.bloxycraftingdead.block.Militaryradioslab01Block;
import net.mcreator.bloxycraftingdead.block.Militaryradioblock05Block;
import net.mcreator.bloxycraftingdead.block.Militaryradioblock04Block;
import net.mcreator.bloxycraftingdead.block.MilitaryRadioBlock03Block;
import net.mcreator.bloxycraftingdead.block.MilitaryRadioBlock02Block;
import net.mcreator.bloxycraftingdead.block.MilitaryRadioBlock01Block;
import net.mcreator.bloxycraftingdead.block.MetalwightBlock;
import net.mcreator.bloxycraftingdead.block.MetalredRecoveredBlock;
import net.mcreator.bloxycraftingdead.block.MetalredRecovered2Block;
import net.mcreator.bloxycraftingdead.block.MetalredBlock;
import net.mcreator.bloxycraftingdead.block.MetalorangeBlock;
import net.mcreator.bloxycraftingdead.block.MetalgreenBlock;
import net.mcreator.bloxycraftingdead.block.MetalblueBlock;
import net.mcreator.bloxycraftingdead.block.MetalBlock;
import net.mcreator.bloxycraftingdead.block.LightSwitchBlock;
import net.mcreator.bloxycraftingdead.block.LeftTurnedOfficeChairBlock;
import net.mcreator.bloxycraftingdead.block.LeftTurnedDirtyOfficeChairBlock;
import net.mcreator.bloxycraftingdead.block.LaptopBlock;
import net.mcreator.bloxycraftingdead.block.LabEquipment04Block;
import net.mcreator.bloxycraftingdead.block.LabEquipment03Block;
import net.mcreator.bloxycraftingdead.block.LabEquipment031Block;
import net.mcreator.bloxycraftingdead.block.LabEquipment02Block;
import net.mcreator.bloxycraftingdead.block.LabEquipment01Block;
import net.mcreator.bloxycraftingdead.block.IndustrialtielsbrowncrackedBlock;
import net.mcreator.bloxycraftingdead.block.IndustrialtielsbrownBlock;
import net.mcreator.bloxycraftingdead.block.GeneratorBlock;
import net.mcreator.bloxycraftingdead.block.GasTankGreyBlock;
import net.mcreator.bloxycraftingdead.block.GasTankBlueBlock;
import net.mcreator.bloxycraftingdead.block.GasTankBlock;
import net.mcreator.bloxycraftingdead.block.GasCanRedBlock;
import net.mcreator.bloxycraftingdead.block.GasCanGreenBlock;
import net.mcreator.bloxycraftingdead.block.GasCanBlueBlock;
import net.mcreator.bloxycraftingdead.block.FlatscreenBlock;
import net.mcreator.bloxycraftingdead.block.ElectricalSocketBlock;
import net.mcreator.bloxycraftingdead.block.DoubleGasCanRedBlock;
import net.mcreator.bloxycraftingdead.block.DoubleGasCanGreenBlock;
import net.mcreator.bloxycraftingdead.block.DoubleGasCanBlueBlock;
import net.mcreator.bloxycraftingdead.block.DirtyToiletBlock;
import net.mcreator.bloxycraftingdead.block.DirtySmallMirrorBlock;
import net.mcreator.bloxycraftingdead.block.DirtySinkBlock;
import net.mcreator.bloxycraftingdead.block.DirtyOfficeChairBlock;
import net.mcreator.bloxycraftingdead.block.DirtyLaptopBlock;
import net.mcreator.bloxycraftingdead.block.DirtyComputerBlock;
import net.mcreator.bloxycraftingdead.block.DirtyBigMirrorBlock;
import net.mcreator.bloxycraftingdead.block.DestroyedComputerBlock;
import net.mcreator.bloxycraftingdead.block.CrackedSmallMirrorBlock;
import net.mcreator.bloxycraftingdead.block.CrackedComputerBlock;
import net.mcreator.bloxycraftingdead.block.CrackedBigMirrorBlock;
import net.mcreator.bloxycraftingdead.block.ComputerBlock;
import net.mcreator.bloxycraftingdead.block.ClothingRackRightBlock;
import net.mcreator.bloxycraftingdead.block.ClothingRackLeftBlock;
import net.mcreator.bloxycraftingdead.block.CeilingLightBlock;
import net.mcreator.bloxycraftingdead.block.Carlights012aBlock;
import net.mcreator.bloxycraftingdead.block.Carlights012Block;
import net.mcreator.bloxycraftingdead.block.Carlights011aBlock;
import net.mcreator.bloxycraftingdead.block.Carlights011Block;
import net.mcreator.bloxycraftingdead.block.Carlights010aBlock;
import net.mcreator.bloxycraftingdead.block.Carlights010Block;
import net.mcreator.bloxycraftingdead.block.CampingChairYellowBlock;
import net.mcreator.bloxycraftingdead.block.CampingChairRedBlock;
import net.mcreator.bloxycraftingdead.block.CampingChairPurpleBlock;
import net.mcreator.bloxycraftingdead.block.CampingChairPinkBlock;
import net.mcreator.bloxycraftingdead.block.CampingChairOrangeBlock;
import net.mcreator.bloxycraftingdead.block.CampingChairGreenBlock;
import net.mcreator.bloxycraftingdead.block.CampingChairBlueBlock;
import net.mcreator.bloxycraftingdead.block.CampingChairBlackBlock;
import net.mcreator.bloxycraftingdead.block.CampfireBlock;
import net.mcreator.bloxycraftingdead.block.Camera03Block;
import net.mcreator.bloxycraftingdead.block.Camera02Block;
import net.mcreator.bloxycraftingdead.block.Camera01Block;
import net.mcreator.bloxycraftingdead.block.BrokenSmallMirrorBlock;
import net.mcreator.bloxycraftingdead.block.BrokenLaptopBlock;
import net.mcreator.bloxycraftingdead.block.BrokenCeilingLightBlock;
import net.mcreator.bloxycraftingdead.block.BrokenBigMirrorBlock;
import net.mcreator.bloxycraftingdead.block.Bricks04Block;
import net.mcreator.bloxycraftingdead.block.Bricks03Block;
import net.mcreator.bloxycraftingdead.block.Bricks02Block;
import net.mcreator.bloxycraftingdead.block.Bricks01Block;
import net.mcreator.bloxycraftingdead.block.BoxBlock;
import net.mcreator.bloxycraftingdead.block.Box04Block;
import net.mcreator.bloxycraftingdead.block.Box03Block;
import net.mcreator.bloxycraftingdead.block.Box032Block;
import net.mcreator.bloxycraftingdead.block.Box031Block;
import net.mcreator.bloxycraftingdead.block.Box02Block;
import net.mcreator.bloxycraftingdead.block.Box01Block;
import net.mcreator.bloxycraftingdead.block.BodyBagBlock;
import net.mcreator.bloxycraftingdead.block.BloodySinkBlock;
import net.mcreator.bloxycraftingdead.block.BlockadeBlock;
import net.mcreator.bloxycraftingdead.block.BigMirrorBlock;
import net.mcreator.bloxycraftingdead.block.BathroomtilesBlock;
import net.mcreator.bloxycraftingdead.block.BaseSurvivorShelfBlock;
import net.mcreator.bloxycraftingdead.block.BarrelRedBlock;
import net.mcreator.bloxycraftingdead.block.BarrelGreyBlock;
import net.mcreator.bloxycraftingdead.block.BarrelGreenBlock;
import net.mcreator.bloxycraftingdead.block.BarrelBlueBlock;
import net.mcreator.bloxycraftingdead.block.AnimatedPowerboxBlock;
import net.mcreator.bloxycraftingdead.block.AngledFenceTopBlock;
import net.mcreator.bloxycraftingdead.block.AlarmLightBlock;
import net.mcreator.bloxycraftingdead.BloxycraftingdeadMod;

public class BloxycraftingdeadModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, BloxycraftingdeadMod.MODID);
	public static final RegistryObject<Block> TALL_STOP_SIGN = REGISTRY.register("tall_stop_sign", () -> new TallStopSignBlock());
	public static final RegistryObject<Block> WRECKED_STOP_SIGN = REGISTRY.register("wrecked_stop_sign", () -> new WreckedStopSignBlock());
	public static final RegistryObject<Block> SPEED_20_SIGN = REGISTRY.register("speed_20_sign", () -> new Speed20SignBlock());
	public static final RegistryObject<Block> SPEED_25_SIGN = REGISTRY.register("speed_25_sign", () -> new Speed25SignBlock());
	public static final RegistryObject<Block> SPEED_30_SIGN = REGISTRY.register("speed_30_sign", () -> new Speed30SignBlock());
	public static final RegistryObject<Block> SPEED_35_SIGN = REGISTRY.register("speed_35_sign", () -> new Speed35SignBlock());
	public static final RegistryObject<Block> SPEED_40_SIGN = REGISTRY.register("speed_40_sign", () -> new Speed40SignBlock());
	public static final RegistryObject<Block> SPEED_45SIGN = REGISTRY.register("speed_45sign", () -> new Speed45signBlock());
	public static final RegistryObject<Block> BARREL_GREY = REGISTRY.register("barrel_grey", () -> new BarrelGreyBlock());
	public static final RegistryObject<Block> WEARED_BARREL_GREY = REGISTRY.register("weared_barrel_grey", () -> new WearedBarrelGreyBlock());
	public static final RegistryObject<Block> TURNED_BARREL_GREY = REGISTRY.register("turned_barrel_grey", () -> new TurnedBarrelGreyBlock());
	public static final RegistryObject<Block> WEARED_TURNED_BARREL_GREY = REGISTRY.register("weared_turned_barrel_grey",
			() -> new WearedTurnedBarrelGreyBlock());
	public static final RegistryObject<Block> BARREL_BLUE = REGISTRY.register("barrel_blue", () -> new BarrelBlueBlock());
	public static final RegistryObject<Block> WEARED_BARREL_BLUE = REGISTRY.register("weared_barrel_blue", () -> new WearedBarrelBlueBlock());
	public static final RegistryObject<Block> TURNED_BARREL_BLUE = REGISTRY.register("turned_barrel_blue", () -> new TurnedBarrelBlueBlock());
	public static final RegistryObject<Block> WEARED_TURNED_BARREL_BLUE = REGISTRY.register("weared_turned_barrel_blue",
			() -> new WearedTurnedBarrelBlueBlock());
	public static final RegistryObject<Block> BARREL_GREEN = REGISTRY.register("barrel_green", () -> new BarrelGreenBlock());
	public static final RegistryObject<Block> WEARED_BARREL_GREEN = REGISTRY.register("weared_barrel_green", () -> new WearedBarrelGreenBlock());
	public static final RegistryObject<Block> TURNED_BARREL_GREEN = REGISTRY.register("turned_barrel_green", () -> new TurnedBarrelGreenBlock());
	public static final RegistryObject<Block> WEARED_TURNED_BARREL_GREEN = REGISTRY.register("weared_turned_barrel_green",
			() -> new WearedTurnedBarrelGreenBlock());
	public static final RegistryObject<Block> BARREL_RED = REGISTRY.register("barrel_red", () -> new BarrelRedBlock());
	public static final RegistryObject<Block> WEARED_BARREL_RED = REGISTRY.register("weared_barrel_red", () -> new WearedBarrelRedBlock());
	public static final RegistryObject<Block> TURNED_BARREL_RED = REGISTRY.register("turned_barrel_red", () -> new TurnedBarrelRedBlock());
	public static final RegistryObject<Block> WEARED_TURNED_BARREL_RED = REGISTRY.register("weared_turned_barrel_red",
			() -> new WearedTurnedBarrelRedBlock());
	public static final RegistryObject<Block> BATHROOMTILES = REGISTRY.register("bathroomtiles", () -> new BathroomtilesBlock());
	public static final RegistryObject<Block> BRICKS_01 = REGISTRY.register("bricks_01", () -> new Bricks01Block());
	public static final RegistryObject<Block> BRICKS_02 = REGISTRY.register("bricks_02", () -> new Bricks02Block());
	public static final RegistryObject<Block> BRICKS_03 = REGISTRY.register("bricks_03", () -> new Bricks03Block());
	public static final RegistryObject<Block> BRICKS_04 = REGISTRY.register("bricks_04", () -> new Bricks04Block());
	public static final RegistryObject<Block> INDUSTRIALTIELSBROWN = REGISTRY.register("industrialtielsbrown", () -> new IndustrialtielsbrownBlock());
	public static final RegistryObject<Block> INDUSTRIALTIELSBROWNCRACKED = REGISTRY.register("industrialtielsbrowncracked",
			() -> new IndustrialtielsbrowncrackedBlock());
	public static final RegistryObject<Block> METAL = REGISTRY.register("metal", () -> new MetalBlock());
	public static final RegistryObject<Block> METALBLUE = REGISTRY.register("metalblue", () -> new MetalblueBlock());
	public static final RegistryObject<Block> METALGREEN = REGISTRY.register("metalgreen", () -> new MetalgreenBlock());
	public static final RegistryObject<Block> METALORANGE = REGISTRY.register("metalorange", () -> new MetalorangeBlock());
	public static final RegistryObject<Block> METALRED = REGISTRY.register("metalred", () -> new MetalredBlock());
	public static final RegistryObject<Block> METALRED_RECOVERED = REGISTRY.register("metalred_recovered", () -> new MetalredRecoveredBlock());
	public static final RegistryObject<Block> METALRED_RECOVERED_2 = REGISTRY.register("metalred_recovered_2", () -> new MetalredRecovered2Block());
	public static final RegistryObject<Block> METALWIGHT = REGISTRY.register("metalwight", () -> new MetalwightBlock());
	public static final RegistryObject<Block> SOLARPANEL = REGISTRY.register("solarpanel", () -> new SolarpanelBlock());
	public static final RegistryObject<Block> BOX = REGISTRY.register("box", () -> new BoxBlock());
	public static final RegistryObject<Block> O_1 = REGISTRY.register("o_1", () -> new O1Block());
	public static final RegistryObject<Block> O_212 = REGISTRY.register("o_212", () -> new O212Block());
	public static final RegistryObject<Block> BOX_01 = REGISTRY.register("box_01", () -> new Box01Block());
	public static final RegistryObject<Block> BOX_02 = REGISTRY.register("box_02", () -> new Box02Block());
	public static final RegistryObject<Block> BOX_03 = REGISTRY.register("box_03", () -> new Box03Block());
	public static final RegistryObject<Block> BOX_031 = REGISTRY.register("box_031", () -> new Box031Block());
	public static final RegistryObject<Block> BOX_032 = REGISTRY.register("box_032", () -> new Box032Block());
	public static final RegistryObject<Block> BOX_04 = REGISTRY.register("box_04", () -> new Box04Block());
	public static final RegistryObject<Block> CAMERA_01 = REGISTRY.register("camera_01", () -> new Camera01Block());
	public static final RegistryObject<Block> CAMERA_02 = REGISTRY.register("camera_02", () -> new Camera02Block());
	public static final RegistryObject<Block> CAMERA_03 = REGISTRY.register("camera_03", () -> new Camera03Block());
	public static final RegistryObject<Block> CAMPFIRE = REGISTRY.register("campfire", () -> new CampfireBlock());
	public static final RegistryObject<Block> CAMPING_CHAIR_GREEN = REGISTRY.register("camping_chair_green", () -> new CampingChairGreenBlock());
	public static final RegistryObject<Block> CAMPING_CHAIR_RED = REGISTRY.register("camping_chair_red", () -> new CampingChairRedBlock());
	public static final RegistryObject<Block> CAMPING_CHAIR_BLACK = REGISTRY.register("camping_chair_black", () -> new CampingChairBlackBlock());
	public static final RegistryObject<Block> CAMPING_CHAIR_YELLOW = REGISTRY.register("camping_chair_yellow", () -> new CampingChairYellowBlock());
	public static final RegistryObject<Block> CAMPING_CHAIR_BLUE = REGISTRY.register("camping_chair_blue", () -> new CampingChairBlueBlock());
	public static final RegistryObject<Block> CAMPING_CHAIR_PINK = REGISTRY.register("camping_chair_pink", () -> new CampingChairPinkBlock());
	public static final RegistryObject<Block> CAMPING_CHAIR_PURPLE = REGISTRY.register("camping_chair_purple", () -> new CampingChairPurpleBlock());
	public static final RegistryObject<Block> CAMPING_CHAIR_ORANGE = REGISTRY.register("camping_chair_orange", () -> new CampingChairOrangeBlock());
	public static final RegistryObject<Block> WORKING_COMPUTER = REGISTRY.register("working_computer", () -> new WorkingComputerBlock());
	public static final RegistryObject<Block> COMPUTER = REGISTRY.register("computer", () -> new ComputerBlock());
	public static final RegistryObject<Block> DIRTY_COMPUTER = REGISTRY.register("dirty_computer", () -> new DirtyComputerBlock());
	public static final RegistryObject<Block> CRACKED_COMPUTER = REGISTRY.register("cracked_computer", () -> new CrackedComputerBlock());
	public static final RegistryObject<Block> DESTROYED_COMPUTER = REGISTRY.register("destroyed_computer", () -> new DestroyedComputerBlock());
	public static final RegistryObject<Block> GAS_CAN_RED = REGISTRY.register("gas_can_red", () -> new GasCanRedBlock());
	public static final RegistryObject<Block> TURNED_GAS_CAN_RED = REGISTRY.register("turned_gas_can_red", () -> new TurnedGasCanRedBlock());
	public static final RegistryObject<Block> DOUBLE_GAS_CAN_RED = REGISTRY.register("double_gas_can_red", () -> new DoubleGasCanRedBlock());
	public static final RegistryObject<Block> GAS_CAN_BLUE = REGISTRY.register("gas_can_blue", () -> new GasCanBlueBlock());
	public static final RegistryObject<Block> TURNED_GAS_CAN_BLUE = REGISTRY.register("turned_gas_can_blue", () -> new TurnedGasCanBlueBlock());
	public static final RegistryObject<Block> DOUBLE_GAS_CAN_BLUE = REGISTRY.register("double_gas_can_blue", () -> new DoubleGasCanBlueBlock());
	public static final RegistryObject<Block> GAS_CAN_GREEN = REGISTRY.register("gas_can_green", () -> new GasCanGreenBlock());
	public static final RegistryObject<Block> TURNED_GAS_CAN_GREEN = REGISTRY.register("turned_gas_can_green", () -> new TurnedGasCanGreenBlock());
	public static final RegistryObject<Block> DOUBLE_GAS_CAN_GREEN = REGISTRY.register("double_gas_can_green", () -> new DoubleGasCanGreenBlock());
	public static final RegistryObject<Block> GAS_TANK = REGISTRY.register("gas_tank", () -> new GasTankBlock());
	public static final RegistryObject<Block> GAS_TANK_BLUE = REGISTRY.register("gas_tank_blue", () -> new GasTankBlueBlock());
	public static final RegistryObject<Block> GAS_TANK_GREY = REGISTRY.register("gas_tank_grey", () -> new GasTankGreyBlock());
	public static final RegistryObject<Block> GENERATOR = REGISTRY.register("generator", () -> new GeneratorBlock());
	public static final RegistryObject<Block> CARLIGHTS_010A = REGISTRY.register("carlights_010a", () -> new Carlights010aBlock());
	public static final RegistryObject<Block> CARLIGHTS_010 = REGISTRY.register("carlights_010", () -> new Carlights010Block());
	public static final RegistryObject<Block> CARLIGHTS_011A = REGISTRY.register("carlights_011a", () -> new Carlights011aBlock());
	public static final RegistryObject<Block> CARLIGHTS_011 = REGISTRY.register("carlights_011", () -> new Carlights011Block());
	public static final RegistryObject<Block> CARLIGHTS_012A = REGISTRY.register("carlights_012a", () -> new Carlights012aBlock());
	public static final RegistryObject<Block> CARLIGHTS_012 = REGISTRY.register("carlights_012", () -> new Carlights012Block());
	public static final RegistryObject<Block> LAB_EQUIPMENT_01 = REGISTRY.register("lab_equipment_01", () -> new LabEquipment01Block());
	public static final RegistryObject<Block> LAB_EQUIPMENT_02 = REGISTRY.register("lab_equipment_02", () -> new LabEquipment02Block());
	public static final RegistryObject<Block> LAB_EQUIPMENT_03 = REGISTRY.register("lab_equipment_03", () -> new LabEquipment03Block());
	public static final RegistryObject<Block> LAB_EQUIPMENT_031 = REGISTRY.register("lab_equipment_031", () -> new LabEquipment031Block());
	public static final RegistryObject<Block> LAB_EQUIPMENT_04 = REGISTRY.register("lab_equipment_04", () -> new LabEquipment04Block());
	public static final RegistryObject<Block> LAPTOP = REGISTRY.register("laptop", () -> new LaptopBlock());
	public static final RegistryObject<Block> DIRTY_LAPTOP = REGISTRY.register("dirty_laptop", () -> new DirtyLaptopBlock());
	public static final RegistryObject<Block> WORKING_LAPTOP = REGISTRY.register("working_laptop", () -> new WorkingLaptopBlock());
	public static final RegistryObject<Block> BROKEN_LAPTOP = REGISTRY.register("broken_laptop", () -> new BrokenLaptopBlock());
	public static final RegistryObject<Block> ELECTRICAL_SOCKET = REGISTRY.register("electrical_socket", () -> new ElectricalSocketBlock());
	public static final RegistryObject<Block> LIGHT_SWITCH = REGISTRY.register("light_switch", () -> new LightSwitchBlock());
	public static final RegistryObject<Block> MILITARY_RADIO_BLOCK_01 = REGISTRY.register("military_radio_block_01",
			() -> new MilitaryRadioBlock01Block());
	public static final RegistryObject<Block> MILITARY_RADIO_BLOCK_02 = REGISTRY.register("military_radio_block_02",
			() -> new MilitaryRadioBlock02Block());
	public static final RegistryObject<Block> MILITARY_RADIO_BLOCK_03 = REGISTRY.register("military_radio_block_03",
			() -> new MilitaryRadioBlock03Block());
	public static final RegistryObject<Block> MILITARYRADIOBLOCK_04 = REGISTRY.register("militaryradioblock_04",
			() -> new Militaryradioblock04Block());
	public static final RegistryObject<Block> MILITARYRADIOBLOCK_05 = REGISTRY.register("militaryradioblock_05",
			() -> new Militaryradioblock05Block());
	public static final RegistryObject<Block> MILITARYRADIOSLAB_01 = REGISTRY.register("militaryradioslab_01", () -> new Militaryradioslab01Block());
	public static final RegistryObject<Block> MILITARYRADIOSLAB_02 = REGISTRY.register("militaryradioslab_02", () -> new Militaryradioslab02Block());
	public static final RegistryObject<Block> MILITARYRADIOSLAB_03 = REGISTRY.register("militaryradioslab_03", () -> new Militaryradioslab03Block());
	public static final RegistryObject<Block> MILITARYRADIOSLAB_04 = REGISTRY.register("militaryradioslab_04", () -> new Militaryradioslab04Block());
	public static final RegistryObject<Block> MILITARYRADIOSLAB_05 = REGISTRY.register("militaryradioslab_05", () -> new Militaryradioslab05Block());
	public static final RegistryObject<Block> MIRROR = REGISTRY.register("mirror", () -> new MirrorBlock());
	public static final RegistryObject<Block> DIRTY_SMALL_MIRROR = REGISTRY.register("dirty_small_mirror", () -> new DirtySmallMirrorBlock());
	public static final RegistryObject<Block> CRACKED_SMALL_MIRROR = REGISTRY.register("cracked_small_mirror", () -> new CrackedSmallMirrorBlock());
	public static final RegistryObject<Block> BROKEN_SMALL_MIRROR = REGISTRY.register("broken_small_mirror", () -> new BrokenSmallMirrorBlock());
	public static final RegistryObject<Block> BIG_MIRROR = REGISTRY.register("big_mirror", () -> new BigMirrorBlock());
	public static final RegistryObject<Block> DIRTY_BIG_MIRROR = REGISTRY.register("dirty_big_mirror", () -> new DirtyBigMirrorBlock());
	public static final RegistryObject<Block> CRACKED_BIG_MIRROR = REGISTRY.register("cracked_big_mirror", () -> new CrackedBigMirrorBlock());
	public static final RegistryObject<Block> BROKEN_BIG_MIRROR = REGISTRY.register("broken_big_mirror", () -> new BrokenBigMirrorBlock());
	public static final RegistryObject<Block> OFFICE_CHAIR = REGISTRY.register("office_chair", () -> new OfficeChairBlock());
	public static final RegistryObject<Block> DIRTY_OFFICE_CHAIR = REGISTRY.register("dirty_office_chair", () -> new DirtyOfficeChairBlock());
	public static final RegistryObject<Block> TURNED_OFFICE_CHAIR = REGISTRY.register("turned_office_chair", () -> new TurnedOfficeChairBlock());
	public static final RegistryObject<Block> TURNED_DIRTY_OFFICE_CHAIR = REGISTRY.register("turned_dirty_office_chair",
			() -> new TurnedDirtyOfficeChairBlock());
	public static final RegistryObject<Block> LEFT_TURNED_OFFICE_CHAIR = REGISTRY.register("left_turned_office_chair",
			() -> new LeftTurnedOfficeChairBlock());
	public static final RegistryObject<Block> LEFT_TURNED_DIRTY_OFFICE_CHAIR = REGISTRY.register("left_turned_dirty_office_chair",
			() -> new LeftTurnedDirtyOfficeChairBlock());
	public static final RegistryObject<Block> STORESHELFBOX_01 = REGISTRY.register("storeshelfbox_01", () -> new Storeshelfbox01Block());
	public static final RegistryObject<Block> STORESHELFBOX_01A = REGISTRY.register("storeshelfbox_01a", () -> new Storeshelfbox01aBlock());
	public static final RegistryObject<Block> STORESHELFBOX_02 = REGISTRY.register("storeshelfbox_02", () -> new Storeshelfbox02Block());
	public static final RegistryObject<Block> STORESHELFBOX_02A = REGISTRY.register("storeshelfbox_02a", () -> new Storeshelfbox02aBlock());
	public static final RegistryObject<Block> STORESHELFBOX_03 = REGISTRY.register("storeshelfbox_03", () -> new Storeshelfbox03Block());
	public static final RegistryObject<Block> STORESHELFBOX_03A = REGISTRY.register("storeshelfbox_03a", () -> new Storeshelfbox03aBlock());
	public static final RegistryObject<Block> STORESHELFBOX_04 = REGISTRY.register("storeshelfbox_04", () -> new Storeshelfbox04Block());
	public static final RegistryObject<Block> STORESHELFBOX_04A = REGISTRY.register("storeshelfbox_04a", () -> new Storeshelfbox04aBlock());
	public static final RegistryObject<Block> STORESHELFCAN_01 = REGISTRY.register("storeshelfcan_01", () -> new Storeshelfcan01Block());
	public static final RegistryObject<Block> STORESHELFCAN_01A = REGISTRY.register("storeshelfcan_01a", () -> new Storeshelfcan01aBlock());
	public static final RegistryObject<Block> STORESHELFCAN_02 = REGISTRY.register("storeshelfcan_02", () -> new Storeshelfcan02Block());
	public static final RegistryObject<Block> STORESHELFCAN_02A = REGISTRY.register("storeshelfcan_02a", () -> new Storeshelfcan02aBlock());
	public static final RegistryObject<Block> STORESHELFCAN_03 = REGISTRY.register("storeshelfcan_03", () -> new Storeshelfcan03Block());
	public static final RegistryObject<Block> STORESHELFCAN_03A = REGISTRY.register("storeshelfcan_03a", () -> new Storeshelfcan03aBlock());
	public static final RegistryObject<Block> STORESHELFCAN_04 = REGISTRY.register("storeshelfcan_04", () -> new Storeshelfcan04Block());
	public static final RegistryObject<Block> STORESHELFCAN_04A = REGISTRY.register("storeshelfcan_04a", () -> new Storeshelfcan04aBlock());
	public static final RegistryObject<Block> STORESHELFEMPTY_01 = REGISTRY.register("storeshelfempty_01", () -> new Storeshelfempty01Block());
	public static final RegistryObject<Block> STORESHELFEMPTY_01A = REGISTRY.register("storeshelfempty_01a", () -> new Storeshelfempty01aBlock());
	public static final RegistryObject<Block> STORESHELFEMPTY_02 = REGISTRY.register("storeshelfempty_02", () -> new Storeshelfempty02Block());
	public static final RegistryObject<Block> STORESHELFEMPTY_02A = REGISTRY.register("storeshelfempty_02a", () -> new Storeshelfempty02aBlock());
	public static final RegistryObject<Block> STORESHELFEMPTY_03 = REGISTRY.register("storeshelfempty_03", () -> new Storeshelfempty03Block());
	public static final RegistryObject<Block> STORESHELFEMPTY_03A = REGISTRY.register("storeshelfempty_03a", () -> new Storeshelfempty03aBlock());
	public static final RegistryObject<Block> STORESHELFEMPTY_04 = REGISTRY.register("storeshelfempty_04", () -> new Storeshelfempty04Block());
	public static final RegistryObject<Block> STORESHELFEMPTY_04A = REGISTRY.register("storeshelfempty_04a", () -> new Storeshelfempty04aBlock());
	public static final RegistryObject<Block> SINK = REGISTRY.register("sink", () -> new SinkBlock());
	public static final RegistryObject<Block> DIRTY_SINK = REGISTRY.register("dirty_sink", () -> new DirtySinkBlock());
	public static final RegistryObject<Block> BLOODY_SINK = REGISTRY.register("bloody_sink", () -> new BloodySinkBlock());
	public static final RegistryObject<Block> SKELETON_010 = REGISTRY.register("skeleton_010", () -> new Skeleton010Block());
	public static final RegistryObject<Block> SKELETON_011 = REGISTRY.register("skeleton_011", () -> new Skeleton011Block());
	public static final RegistryObject<Block> SKELETON_010AT_1 = REGISTRY.register("skeleton_010at_1", () -> new Skeleton010at1Block());
	public static final RegistryObject<Block> SKELETON_011AT_1 = REGISTRY.register("skeleton_011at_1", () -> new Skeleton011at1Block());
	public static final RegistryObject<Block> SKELETON_012AT_1 = REGISTRY.register("skeleton_012at_1", () -> new Skeleton012at1Block());
	public static final RegistryObject<Block> SKELETON_010BT_1 = REGISTRY.register("skeleton_010bt_1", () -> new Skeleton010bt1Block());
	public static final RegistryObject<Block> SKELETON_011BT_1 = REGISTRY.register("skeleton_011bt_1", () -> new Skeleton011bt1Block());
	public static final RegistryObject<Block> SKELETON_012BT_1 = REGISTRY.register("skeleton_012bt_1", () -> new Skeleton012bt1Block());
	public static final RegistryObject<Block> SKELETON_010CT_1 = REGISTRY.register("skeleton_010ct_1", () -> new Skeleton010ct1Block());
	public static final RegistryObject<Block> SKELETON_011CT_1 = REGISTRY.register("skeleton_011ct_1", () -> new Skeleton011ct1Block());
	public static final RegistryObject<Block> SKELETON_012CT_1 = REGISTRY.register("skeleton_012ct_1", () -> new Skeleton012ct1Block());
	public static final RegistryObject<Block> SKELETON_010DT_1 = REGISTRY.register("skeleton_010dt_1", () -> new Skeleton010dt1Block());
	public static final RegistryObject<Block> SKELETON_011DT_1 = REGISTRY.register("skeleton_011dt_1", () -> new Skeleton011dt1Block());
	public static final RegistryObject<Block> SKELETON_012DT_1 = REGISTRY.register("skeleton_012dt_1", () -> new Skeleton012dt1Block());
	public static final RegistryObject<Block> SKELETON_010ET_1 = REGISTRY.register("skeleton_010et_1", () -> new Skeleton010et1Block());
	public static final RegistryObject<Block> SKELETON_011ET_1 = REGISTRY.register("skeleton_011et_1", () -> new Skeleton011et1Block());
	public static final RegistryObject<Block> SKELETON_012ET_1 = REGISTRY.register("skeleton_012et_1", () -> new Skeleton012et1Block());
	public static final RegistryObject<Block> SKELETON_010FT_1 = REGISTRY.register("skeleton_010ft_1", () -> new Skeleton010ft1Block());
	public static final RegistryObject<Block> SKELETON_011FT_1 = REGISTRY.register("skeleton_011ft_1", () -> new Skeleton011ft1Block());
	public static final RegistryObject<Block> SKELETON_012FT_1 = REGISTRY.register("skeleton_012ft_1", () -> new Skeleton012ft1Block());
	public static final RegistryObject<Block> SKELETON_020 = REGISTRY.register("skeleton_020", () -> new Skeleton020Block());
	public static final RegistryObject<Block> SKELETON_021 = REGISTRY.register("skeleton_021", () -> new Skeleton021Block());
	public static final RegistryObject<Block> SKELETON_020AT_2 = REGISTRY.register("skeleton_020at_2", () -> new Skeleton020at2Block());
	public static final RegistryObject<Block> SKELETON_021AT_2 = REGISTRY.register("skeleton_021at_2", () -> new Skeleton021at2Block());
	public static final RegistryObject<Block> SKELETON_022AT_2 = REGISTRY.register("skeleton_022at_2", () -> new Skeleton022at2Block());
	public static final RegistryObject<Block> SKELETON_020BT_2 = REGISTRY.register("skeleton_020bt_2", () -> new Skeleton020bt2Block());
	public static final RegistryObject<Block> SKELETON_021BT_2 = REGISTRY.register("skeleton_021bt_2", () -> new Skeleton021bt2Block());
	public static final RegistryObject<Block> SKELETON_022BT_2 = REGISTRY.register("skeleton_022bt_2", () -> new Skeleton022bt2Block());
	public static final RegistryObject<Block> SKELETON_020CT_2 = REGISTRY.register("skeleton_020ct_2", () -> new Skeleton020ct2Block());
	public static final RegistryObject<Block> SKELETON_021CT_2 = REGISTRY.register("skeleton_021ct_2", () -> new Skeleton021ct2Block());
	public static final RegistryObject<Block> SKELETON_022CT_2 = REGISTRY.register("skeleton_022ct_2", () -> new Skeleton022ct2Block());
	public static final RegistryObject<Block> SKELETON_020DT_2 = REGISTRY.register("skeleton_020dt_2", () -> new Skeleton020dt2Block());
	public static final RegistryObject<Block> SKELETON_021DT_2 = REGISTRY.register("skeleton_021dt_2", () -> new Skeleton021dt2Block());
	public static final RegistryObject<Block> SKELETON_022DT_2 = REGISTRY.register("skeleton_022dt_2", () -> new Skeleton022dt2Block());
	public static final RegistryObject<Block> SKELETON_020ET_2 = REGISTRY.register("skeleton_020et_2", () -> new Skeleton020et2Block());
	public static final RegistryObject<Block> SKELETON_021ET_2 = REGISTRY.register("skeleton_021et_2", () -> new Skeleton021et2Block());
	public static final RegistryObject<Block> SKELETON_022ET_2 = REGISTRY.register("skeleton_022et_2", () -> new Skeleton022et2Block());
	public static final RegistryObject<Block> SKELETON_020FT_2 = REGISTRY.register("skeleton_020ft_2", () -> new Skeleton020ft2Block());
	public static final RegistryObject<Block> SKELETON_021FT_2 = REGISTRY.register("skeleton_021ft_2", () -> new Skeleton021ft2Block());
	public static final RegistryObject<Block> SKELETON_022FT_2 = REGISTRY.register("skeleton_022ft_2", () -> new Skeleton022ft2Block());
	public static final RegistryObject<Block> SKELETON_030 = REGISTRY.register("skeleton_030", () -> new Skeleton030Block());
	public static final RegistryObject<Block> SKELETON_031 = REGISTRY.register("skeleton_031", () -> new Skeleton031Block());
	public static final RegistryObject<Block> SKELETON_032 = REGISTRY.register("skeleton_032", () -> new Skeleton032Block());
	public static final RegistryObject<Block> TOOL_01 = REGISTRY.register("tool_01", () -> new Tool01Block());
	public static final RegistryObject<Block> TOOL_02 = REGISTRY.register("tool_02", () -> new Tool02Block());
	public static final RegistryObject<Block> TOOL_03 = REGISTRY.register("tool_03", () -> new Tool03Block());
	public static final RegistryObject<Block> TOOL_04 = REGISTRY.register("tool_04", () -> new Tool04Block());
	public static final RegistryObject<Block> TOILET = REGISTRY.register("toilet", () -> new ToiletBlock());
	public static final RegistryObject<Block> DIRTY_TOILET = REGISTRY.register("dirty_toilet", () -> new DirtyToiletBlock());
	public static final RegistryObject<Block> USED_TOILET = REGISTRY.register("used_toilet", () -> new UsedToiletBlock());
	public static final RegistryObject<Block> USED_DIRTY_TOILET = REGISTRY.register("used_dirty_toilet", () -> new UsedDirtyToiletBlock());
	public static final RegistryObject<Block> WRECKED_TV = REGISTRY.register("wrecked_tv", () -> new WreckedTVBlock());
	public static final RegistryObject<Block> TV = REGISTRY.register("tv", () -> new TVBlock());
	public static final RegistryObject<Block> FLATSCREEN = REGISTRY.register("flatscreen", () -> new FlatscreenBlock());
	public static final RegistryObject<Block> WRECKED_FLATSCREEN = REGISTRY.register("wrecked_flatscreen", () -> new WreckedFlatscreenBlock());
	public static final RegistryObject<Block> WORKBENCH = REGISTRY.register("workbench", () -> new WorkbenchBlock());
	public static final RegistryObject<Block> CLOTHING_RACK_LEFT = REGISTRY.register("clothing_rack_left", () -> new ClothingRackLeftBlock());
	public static final RegistryObject<Block> CLOTHING_RACK_RIGHT = REGISTRY.register("clothing_rack_right", () -> new ClothingRackRightBlock());
	public static final RegistryObject<Block> ALARM_LIGHT = REGISTRY.register("alarm_light", () -> new AlarmLightBlock());
	public static final RegistryObject<Block> ANGLED_FENCE_TOP = REGISTRY.register("angled_fence_top", () -> new AngledFenceTopBlock());
	public static final RegistryObject<Block> BASE_SURVIVOR_SHELF = REGISTRY.register("base_survivor_shelf", () -> new BaseSurvivorShelfBlock());
	public static final RegistryObject<Block> BLOCKADE = REGISTRY.register("blockade", () -> new BlockadeBlock());
	public static final RegistryObject<Block> BODY_BAG = REGISTRY.register("body_bag", () -> new BodyBagBlock());
	public static final RegistryObject<Block> BROKEN_CEILING_LIGHT = REGISTRY.register("broken_ceiling_light", () -> new BrokenCeilingLightBlock());
	public static final RegistryObject<Block> CEILING_LIGHT = REGISTRY.register("ceiling_light", () -> new CeilingLightBlock());
	public static final RegistryObject<Block> WOODEN_BARRICADE_WINDOW_01 = REGISTRY.register("wooden_barricade_window_01",
			() -> new WoodenBarricadeWindow01Block());
	public static final RegistryObject<Block> WOODEN_BARRICADE_WINDOW_01A = REGISTRY.register("wooden_barricade_window_01a",
			() -> new WoodenBarricadeWindow01aBlock());
	public static final RegistryObject<Block> WOODENBARRICADEWINDOW_01B = REGISTRY.register("woodenbarricadewindow_01b",
			() -> new Woodenbarricadewindow01bBlock());
	public static final RegistryObject<Block> WOODENBARRICADEWINDOW_01C = REGISTRY.register("woodenbarricadewindow_01c",
			() -> new Woodenbarricadewindow01cBlock());
	public static final RegistryObject<Block> WOODEN_BARRICADE_WINDOW_02 = REGISTRY.register("wooden_barricade_window_02",
			() -> new WoodenBarricadeWindow02Block());
	public static final RegistryObject<Block> WOODEN_BARRICADE_WINDOW_02A = REGISTRY.register("wooden_barricade_window_02a",
			() -> new WoodenBarricadeWindow02aBlock());
	public static final RegistryObject<Block> WOODENBARRICADEWINDOW_02B = REGISTRY.register("woodenbarricadewindow_02b",
			() -> new Woodenbarricadewindow02bBlock());
	public static final RegistryObject<Block> WOODEN_BARRICADE_WINDOW_02C = REGISTRY.register("wooden_barricade_window_02c",
			() -> new WoodenBarricadeWindow02cBlock());
	public static final RegistryObject<Block> WOODEN_BARRICADE_WINDOW_03 = REGISTRY.register("wooden_barricade_window_03",
			() -> new WoodenBarricadeWindow03Block());
	public static final RegistryObject<Block> WOODENBARRICADEWINDOW_03A = REGISTRY.register("woodenbarricadewindow_03a",
			() -> new Woodenbarricadewindow03aBlock());
	public static final RegistryObject<Block> WOODENBARRICADEWINDOW_03B = REGISTRY.register("woodenbarricadewindow_03b",
			() -> new Woodenbarricadewindow03bBlock());
	public static final RegistryObject<Block> WOODENBARRICADEWINDOW_03C = REGISTRY.register("woodenbarricadewindow_03c",
			() -> new Woodenbarricadewindow03cBlock());
	public static final RegistryObject<Block> POWERBOX = REGISTRY.register("powerbox", () -> new PowerboxBlock());
	public static final RegistryObject<Block> ANIMATED_POWERBOX = REGISTRY.register("animated_powerbox", () -> new AnimatedPowerboxBlock());

	@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class ClientSideHandler {
		@SubscribeEvent
		public static void clientSetup(FMLClientSetupEvent event) {
			TallStopSignBlock.registerRenderLayer();
			WreckedStopSignBlock.registerRenderLayer();
			Speed20SignBlock.registerRenderLayer();
			Speed25SignBlock.registerRenderLayer();
			Speed30SignBlock.registerRenderLayer();
			Speed35SignBlock.registerRenderLayer();
			Speed40SignBlock.registerRenderLayer();
			Speed45signBlock.registerRenderLayer();
			BarrelGreyBlock.registerRenderLayer();
			WearedBarrelGreyBlock.registerRenderLayer();
			TurnedBarrelGreyBlock.registerRenderLayer();
			WearedTurnedBarrelGreyBlock.registerRenderLayer();
			BarrelBlueBlock.registerRenderLayer();
			WearedBarrelBlueBlock.registerRenderLayer();
			TurnedBarrelBlueBlock.registerRenderLayer();
			WearedTurnedBarrelBlueBlock.registerRenderLayer();
			BarrelGreenBlock.registerRenderLayer();
			WearedBarrelGreenBlock.registerRenderLayer();
			TurnedBarrelGreenBlock.registerRenderLayer();
			WearedTurnedBarrelGreenBlock.registerRenderLayer();
			BarrelRedBlock.registerRenderLayer();
			WearedBarrelRedBlock.registerRenderLayer();
			TurnedBarrelRedBlock.registerRenderLayer();
			WearedTurnedBarrelRedBlock.registerRenderLayer();
			Box01Block.registerRenderLayer();
			Box02Block.registerRenderLayer();
			Box03Block.registerRenderLayer();
			Box031Block.registerRenderLayer();
			Box032Block.registerRenderLayer();
			Box04Block.registerRenderLayer();
			Camera01Block.registerRenderLayer();
			Camera02Block.registerRenderLayer();
			Camera03Block.registerRenderLayer();
			CampfireBlock.registerRenderLayer();
			CampingChairGreenBlock.registerRenderLayer();
			CampingChairRedBlock.registerRenderLayer();
			CampingChairBlackBlock.registerRenderLayer();
			CampingChairYellowBlock.registerRenderLayer();
			CampingChairBlueBlock.registerRenderLayer();
			CampingChairPinkBlock.registerRenderLayer();
			CampingChairPurpleBlock.registerRenderLayer();
			CampingChairOrangeBlock.registerRenderLayer();
			WorkingComputerBlock.registerRenderLayer();
			ComputerBlock.registerRenderLayer();
			DirtyComputerBlock.registerRenderLayer();
			CrackedComputerBlock.registerRenderLayer();
			DestroyedComputerBlock.registerRenderLayer();
			GasCanRedBlock.registerRenderLayer();
			TurnedGasCanRedBlock.registerRenderLayer();
			DoubleGasCanRedBlock.registerRenderLayer();
			GasCanBlueBlock.registerRenderLayer();
			TurnedGasCanBlueBlock.registerRenderLayer();
			DoubleGasCanBlueBlock.registerRenderLayer();
			GasCanGreenBlock.registerRenderLayer();
			TurnedGasCanGreenBlock.registerRenderLayer();
			DoubleGasCanGreenBlock.registerRenderLayer();
			GasTankBlock.registerRenderLayer();
			GasTankBlueBlock.registerRenderLayer();
			GasTankGreyBlock.registerRenderLayer();
			GeneratorBlock.registerRenderLayer();
			Carlights010aBlock.registerRenderLayer();
			Carlights010Block.registerRenderLayer();
			Carlights011aBlock.registerRenderLayer();
			Carlights011Block.registerRenderLayer();
			Carlights012aBlock.registerRenderLayer();
			Carlights012Block.registerRenderLayer();
			LabEquipment01Block.registerRenderLayer();
			LabEquipment02Block.registerRenderLayer();
			LabEquipment03Block.registerRenderLayer();
			LabEquipment031Block.registerRenderLayer();
			LabEquipment04Block.registerRenderLayer();
			LaptopBlock.registerRenderLayer();
			DirtyLaptopBlock.registerRenderLayer();
			WorkingLaptopBlock.registerRenderLayer();
			BrokenLaptopBlock.registerRenderLayer();
			ElectricalSocketBlock.registerRenderLayer();
			LightSwitchBlock.registerRenderLayer();
			MilitaryRadioBlock01Block.registerRenderLayer();
			MilitaryRadioBlock02Block.registerRenderLayer();
			MilitaryRadioBlock03Block.registerRenderLayer();
			Militaryradioblock04Block.registerRenderLayer();
			Militaryradioblock05Block.registerRenderLayer();
			Militaryradioslab01Block.registerRenderLayer();
			Militaryradioslab02Block.registerRenderLayer();
			Militaryradioslab03Block.registerRenderLayer();
			Militaryradioslab04Block.registerRenderLayer();
			Militaryradioslab05Block.registerRenderLayer();
			MirrorBlock.registerRenderLayer();
			DirtySmallMirrorBlock.registerRenderLayer();
			CrackedSmallMirrorBlock.registerRenderLayer();
			BrokenSmallMirrorBlock.registerRenderLayer();
			BigMirrorBlock.registerRenderLayer();
			DirtyBigMirrorBlock.registerRenderLayer();
			CrackedBigMirrorBlock.registerRenderLayer();
			BrokenBigMirrorBlock.registerRenderLayer();
			OfficeChairBlock.registerRenderLayer();
			DirtyOfficeChairBlock.registerRenderLayer();
			TurnedOfficeChairBlock.registerRenderLayer();
			TurnedDirtyOfficeChairBlock.registerRenderLayer();
			LeftTurnedOfficeChairBlock.registerRenderLayer();
			LeftTurnedDirtyOfficeChairBlock.registerRenderLayer();
			Storeshelfbox01Block.registerRenderLayer();
			Storeshelfbox01aBlock.registerRenderLayer();
			Storeshelfbox02Block.registerRenderLayer();
			Storeshelfbox02aBlock.registerRenderLayer();
			Storeshelfbox03Block.registerRenderLayer();
			Storeshelfbox03aBlock.registerRenderLayer();
			Storeshelfbox04Block.registerRenderLayer();
			Storeshelfbox04aBlock.registerRenderLayer();
			Storeshelfcan01Block.registerRenderLayer();
			Storeshelfcan01aBlock.registerRenderLayer();
			Storeshelfcan02Block.registerRenderLayer();
			Storeshelfcan02aBlock.registerRenderLayer();
			Storeshelfcan03Block.registerRenderLayer();
			Storeshelfcan03aBlock.registerRenderLayer();
			Storeshelfcan04Block.registerRenderLayer();
			Storeshelfcan04aBlock.registerRenderLayer();
			Storeshelfempty01Block.registerRenderLayer();
			Storeshelfempty01aBlock.registerRenderLayer();
			Storeshelfempty02Block.registerRenderLayer();
			Storeshelfempty02aBlock.registerRenderLayer();
			Storeshelfempty03Block.registerRenderLayer();
			Storeshelfempty03aBlock.registerRenderLayer();
			Storeshelfempty04Block.registerRenderLayer();
			Storeshelfempty04aBlock.registerRenderLayer();
			SinkBlock.registerRenderLayer();
			DirtySinkBlock.registerRenderLayer();
			BloodySinkBlock.registerRenderLayer();
			Skeleton010Block.registerRenderLayer();
			Skeleton011Block.registerRenderLayer();
			Skeleton010at1Block.registerRenderLayer();
			Skeleton011at1Block.registerRenderLayer();
			Skeleton012at1Block.registerRenderLayer();
			Skeleton010bt1Block.registerRenderLayer();
			Skeleton011bt1Block.registerRenderLayer();
			Skeleton012bt1Block.registerRenderLayer();
			Skeleton010ct1Block.registerRenderLayer();
			Skeleton011ct1Block.registerRenderLayer();
			Skeleton012ct1Block.registerRenderLayer();
			Skeleton010dt1Block.registerRenderLayer();
			Skeleton011dt1Block.registerRenderLayer();
			Skeleton012dt1Block.registerRenderLayer();
			Skeleton010et1Block.registerRenderLayer();
			Skeleton011et1Block.registerRenderLayer();
			Skeleton012et1Block.registerRenderLayer();
			Skeleton010ft1Block.registerRenderLayer();
			Skeleton011ft1Block.registerRenderLayer();
			Skeleton012ft1Block.registerRenderLayer();
			Skeleton020Block.registerRenderLayer();
			Skeleton021Block.registerRenderLayer();
			Skeleton020at2Block.registerRenderLayer();
			Skeleton021at2Block.registerRenderLayer();
			Skeleton022at2Block.registerRenderLayer();
			Skeleton020bt2Block.registerRenderLayer();
			Skeleton021bt2Block.registerRenderLayer();
			Skeleton022bt2Block.registerRenderLayer();
			Skeleton020ct2Block.registerRenderLayer();
			Skeleton021ct2Block.registerRenderLayer();
			Skeleton022ct2Block.registerRenderLayer();
			Skeleton020dt2Block.registerRenderLayer();
			Skeleton021dt2Block.registerRenderLayer();
			Skeleton022dt2Block.registerRenderLayer();
			Skeleton020et2Block.registerRenderLayer();
			Skeleton021et2Block.registerRenderLayer();
			Skeleton022et2Block.registerRenderLayer();
			Skeleton020ft2Block.registerRenderLayer();
			Skeleton021ft2Block.registerRenderLayer();
			Skeleton022ft2Block.registerRenderLayer();
			Skeleton030Block.registerRenderLayer();
			Skeleton031Block.registerRenderLayer();
			Skeleton032Block.registerRenderLayer();
			Tool01Block.registerRenderLayer();
			Tool02Block.registerRenderLayer();
			Tool03Block.registerRenderLayer();
			Tool04Block.registerRenderLayer();
			ToiletBlock.registerRenderLayer();
			DirtyToiletBlock.registerRenderLayer();
			UsedToiletBlock.registerRenderLayer();
			UsedDirtyToiletBlock.registerRenderLayer();
			WreckedTVBlock.registerRenderLayer();
			TVBlock.registerRenderLayer();
			FlatscreenBlock.registerRenderLayer();
			WreckedFlatscreenBlock.registerRenderLayer();
			WorkbenchBlock.registerRenderLayer();
			ClothingRackLeftBlock.registerRenderLayer();
			ClothingRackRightBlock.registerRenderLayer();
			AlarmLightBlock.registerRenderLayer();
			AngledFenceTopBlock.registerRenderLayer();
			BaseSurvivorShelfBlock.registerRenderLayer();
			BlockadeBlock.registerRenderLayer();
			BodyBagBlock.registerRenderLayer();
			BrokenCeilingLightBlock.registerRenderLayer();
			CeilingLightBlock.registerRenderLayer();
			WoodenBarricadeWindow01Block.registerRenderLayer();
			WoodenBarricadeWindow01aBlock.registerRenderLayer();
			Woodenbarricadewindow01bBlock.registerRenderLayer();
			Woodenbarricadewindow01cBlock.registerRenderLayer();
			WoodenBarricadeWindow02Block.registerRenderLayer();
			WoodenBarricadeWindow02aBlock.registerRenderLayer();
			Woodenbarricadewindow02bBlock.registerRenderLayer();
			WoodenBarricadeWindow02cBlock.registerRenderLayer();
			WoodenBarricadeWindow03Block.registerRenderLayer();
			Woodenbarricadewindow03aBlock.registerRenderLayer();
			Woodenbarricadewindow03bBlock.registerRenderLayer();
			Woodenbarricadewindow03cBlock.registerRenderLayer();
			PowerboxBlock.registerRenderLayer();
			AnimatedPowerboxBlock.registerRenderLayer();
		}
	}
}
